heat_template_version: '2015-04-30'
parameters:
    flavor:
        default: m1.small
        label: Flavor
        type: string
    public_network:
        default: db3b2356-17c7-491e-9b7b-01fc1e946f8d
        label: Public Network ID
        type: string
    sshkeypair:
        label: SSH keypair name
        type: string
resources:
    devserver:
        type: OS::Nova::Server
        properties:
            flavor:
                get_param: flavor
            image: Oracle Linux 7.2
            key_name:
                get_param: sshkeypair
            name:
                str_replace:
                    params:
                        $name:
                            get_param: OS::stack_name
                    template: $name-vm
            networks:
                - network:
                    get_param: public_network
            user_data_format: RAW
            user_data: |
                #cloud-config
                bootcmd:
                    - echo proxy=http://adc-proxy.oracle.com:80 >> /etc/yum.conf

                packages:
                    - git
                    - vim
                    - bash-completion
                    - zlib-devel
                    - bzip2
                    - bzip2-devel
                    - readline-devel
                    - sqlite
                    - sqlite-devel
                    - openssl-devel
                    - libffi-devel

                write_files:
                    - path: /etc/profile.d/proxy.sh
                      owner: root:root
                      permissions: '0755'
                      content: |
                          export http_proxy=http://adc-proxy.oracle.com:80
                          export https_proxy=http://adc-proxy.oracle.com:80
                          export HTTP_PROXY=http://adc-proxy.oracle.com:80
                          export HTTPS_PROXY=http://adc-proxy.oracle.com:80
                          export no_proxy=localhost,127.0.0.1,ccp1,us.oracle.com,oracle.com,labs.nc.tekelec.com
                    - path: /etc/resolv.conf
                      owner: root:root
                      permissions: '0644'
                      content: |
                          nameserver 10.209.76.197
                          nameserver 10.209.76.198
                          nameserver 192.135.82.132
                          search us.oracle.com oraclecorp.com
                    - path: /opt/init.sh
                      owner: root:root
                      permissions: '0755'
                      content: |
                          #!/usr/bin/env bash
                          set -x
                          source /etc/profile.d/proxy.sh
                          git clone http://github.com/yyuu/pyenv.git /opt/pyenv
                          echo 'export PYENV_ROOT="/opt/pyenv"' >> ~/.bash_profile
                          echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
                          echo 'eval "$(pyenv init -)"' >> ~/.bash_profile

                runcmd:
                    - /opt/init.sh
