$schema: http://json-schema.org/draft-04/schema#
title: HOT template generator input specification
type: object
properties:
    params:
        type: object
        properties:
            noampfunction:
                type: string
                description: Server Group Function of the NOAM&P Server Group
                example: UDR-NO
            noampflavor:
                type: string
                description: Nova flavor for the NOAM&P pair
                example: m1.small
            noampprofile:
                type: string
                description: AppWorks hardware profile for the NOAM&P pair
                example: TVOE Guest
            networks:
                type: array
                description: Networks in the NOAM&P Network Element
                items:
                    type: object
                    properties:
                        name:
                            type: string
                            description: Name of the network
                            example: XMI
                        cidr:
                            type: string
                            description: Address of the network in CIDR format
                            example: 192.168.0.0/24
                        routed:
                            type: boolean
                            description: Whether or not the network is a routed network
                            example: true
            globalnetworks:
                type: array
                description: Networks that are not part of any Network Element
                items:
                    type: object
                    properties:
                        name:
                            type: string
                            description: Name of the networks
                            example: XSI
                        cidr:
                            type: string
                            description: Address of the network in CIDR format
                            example: 192.168.100.0/24
                        routed:
                            type: boolean
                            description: Whether or not the network is a routed network
                            example: true
            interfaces:
                type: array
                description: The networks servers in this network element should be connected to
                items:
                    type: string
                    description: Network name
                    example: XMI
            services:
                type: array
                description: Maps services to networks
                items:
                    type: object
                    properties:
                        name:
                            type: string
                            description: Name of the service to map
                            example: Replication
                        interSitePath:
                            type: string
                            description: Network to use for this service when communicating between different Network Elements
                            example: XMI
                        intraSitePath:
                            type: string
                            description: Network to use for this service when communicating within the same Network Element
                            example: IMI
            networkelements:
                type: array
                description: SOAM Network Elements
                items:
                    type: object
                    properties:
                        soamfunction:
                            type: string
                            description: Server Group Function of the SOAM Server Group in this Network element
                            example: NONE
                        soamflavor:
                            type: string
                            description: Nova flavor for the SOAM pair in this Network Element
                            example: m1.small
                        soamprofile:
                            type: string
                            description: AppWorks hardware profile for this SOAM pair
                            example: TVOE Guest
                        networks:
                            type: array
                            description: Networks in the SOAM Network Element
                            items:
                                type: object
                                properties:
                                    name:
                                        type: string
                                        description: Name of the network
                                        example: XMI
                                    cidr:
                                        type: string
                                        description: Address of the network in CIDR format
                                        example: 192.168.0.0/24
                                    routed:
                                        type: boolean
                                        description: Whether or not the network is a routed network
                                        example: true
                        interfaces:
                            type: array
                            description: The networks SO servers in this network element should be connected to
                            items:
                                type: string
                                description: Network name
                                example: XMI
                        mpservergroups:
                            type: array
                            description: MP Server Groups in this Network Element
                            items:
                                type: object
                                properties:
                                    function:
                                        type: string
                                        description: Server Group Function of this MP Server Group
                                        example: UDR-MP (multi-active cluster)
                                    mpflavor:
                                        type: string
                                        description: Nova flavor for this MP Server Group
                                        example: m1.small
                                    mpprofile:
                                        type: string
                                        description: AppWorks hardware profile for this MP Server Group
                                        example: TVOE Guest
                                    mpcount:
                                        type: integer
                                        description: The number of MPs in this Server Group
                                        example: 2
                                    interfaces:
                                        type: array
                                        description: The networks MP servers in this Server Group should be connected to
                                        items:
                                            type: string
                                            description: Network name
                                            example: XMI
    extras:
        type: array
        description: Extra servers to include in the template.
        items:
            type: object
            properties:
                name:
                    type: string
                    description: The name of this VM
                    example: seagull
                image:
                    type: string
                    description: The image to use for this VM
                    example: MEATOS6.106.0
                flavor:
                    type: string
                    description: Nova flavor to use for this VM
                    example: m1.large
                interfaces:
                    type: array
                    description: Networks this extra server should be connected to
                    items:
                        type: object
                        properties:
                            nename:
                                type: string
                                description: Name of the Network Element containing the networks ("GLOBAL" for networks not in Network Elements)
                                example: NO_NE
                            network:
                                type: string
                                description: Name of the network
                                example: XMI

                user-data:
                    type: string
                    description: User data to pass to cloud-init for this VM
                    example: |
                        #cloud-config

                        packages:
                            - seagull
