$schema: http://json-schema.org/draft-04/schema#
title: HOT template generator input specification
type: object
properties:
    params:
        type: object
        properties:
            noampfunction:
                type: string
                description: Server Group Function of the NOAM&P Server Group
                example: UDR-NO
            noampflavor:
                type: string
                description: Nova flavor for the NOAM&P pair
                example: m1.small
            supernet:
                type: string
                description: Network to subnet to provide routed networks
                example: 192.168.23.0/24
            networkelements:
                type: array
                description: SOAM Network Elements
                items:
                    type: object
                    properties:
                        soamfunction:
                            type: string
                            description: Server Group Function of the SOAM Server Group in this Network element
                            example: NONE
                        soamflavor:
                            type: string
                            description: Nova flavor for the SOAM pair in this Network Element
                            example: m1.small
                        mpservergroups:
                            type: array
                            description: MP Server Groups in this Network Element
                            items:
                                type: object
                                properties:
                                    function:
                                        type: string
                                        description: Server Group Function of this MP Server Group
                                        example: UDR-MP (multi-active cluster)
                                    mpflavor:
                                        type: string
                                        description: Nova flavor for this MP Server Group
                                        example: m1.small
                                    mpcount:
                                        type: integer
                                        description: The number of MPs in this Server Group
                                        example: 2
    extras:
        type: array
        description: Extra servers to include in the template. They will be connected to the NOAM&P Network Element WAN network, as well as the XSI network.
        items:
            type: object
            properties:
                name:
                    type: string
                    description: The name of this VM
                    example: seagull
                image:
                    type: string
                    description: The image to use for this VM
                    example: MEATOS6.106.0
                flavor:
                    type: string
                    description: Nova flavor to use for this VM
                    example: m1.large
                user-data:
                    type: string
                    description: User data to pass to cloud-init for this VM
                    example: |
                        #cloud-config

                        packages:
                            - seagull
